# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongo_doc-rails}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Elliot Crosby-McCullough, Les Hill"]
  s.date = %q{2010-04-08}
  s.description = %q{MongoDoc-Rails provides an interface between the MongoDoc::Document and the Rails 3 ActionPack.}
  s.email = %q{elliot.cm@gmail.com, leshill@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/mongo_doc-rails.rb",
     "lib/mongo_doc/active_model.rb",
     "lib/mongo_doc/active_model/active_model_compliance.rb",
     "lib/mongo_doc/active_model/validations.rb",
     "mongo_doc-rails.gemspec",
     "spec/active_model/active_model_compliance_spec.rb",
     "spec/active_model/validations_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/elliotcm/mongo_doc-rails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Rails 3 integration for MongoDoc}
  s.test_files = [
    "spec/active_model/active_model_compliance_spec.rb",
     "spec/active_model/validations_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongo_doc>, [">= 0.5.0"])
      s.add_runtime_dependency(%q<activemodel>, [">= 3.0.0.beta"])
      s.add_development_dependency(%q<rspec>, ["= 1.3.0"])
    else
      s.add_dependency(%q<mongo_doc>, [">= 0.5.0"])
      s.add_dependency(%q<activemodel>, [">= 3.0.0.beta"])
      s.add_dependency(%q<rspec>, ["= 1.3.0"])
    end
  else
    s.add_dependency(%q<mongo_doc>, [">= 0.5.0"])
    s.add_dependency(%q<activemodel>, [">= 3.0.0.beta"])
    s.add_dependency(%q<rspec>, ["= 1.3.0"])
  end
end

